### ISSUE TITLE
Deleting a Board

### ISSUE THREAD

**Issue by kwadroke** [shellyln/kanban-board-app#1]
How do I remove a board, archive board, or at least keep a board from being listed?
I'd like to remove _Welcome Board_ from the list.

**Comment by shellyln** [comment]
Hi, @kwadroke !
To remove a board, do the following:
1. Select and display the board you want to delete from the board list.
1. Click "Edit" from the menu (Kanban|Calendar|Edit) to display the board setting page.
1. Click the "Delete" button in the upper right corner, enter "Delete board" in the confirmation dialog, and click "DELETE".

**Comment by kwadroke** [comment]
Thank you
